name: webart_resource
version: 0.0.1
description: A simple way to reorganize resources in your web application
author: thisLight <l1589002388@gmail.com>
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  webart: ^0.2.6
dev_dependencies:
  test: "^0.12.30"
